<?php

return [
    'items' => [
        [
            'id' => 1,
            'slug' => 'creative-innovation',
            'name' => 'Creative Innovation',
            'type' => 'Tim',
            'category_badge' => 'SD / SMP / SMA',
            'target_level' => 'Tingkat SD, SMP, dan SMA / sederajat',
            'tagline' => 'Inovasi robotika bebas & kreatif untuk memecahkan permasalahan nyata dengan teknologi AI dan IoT.',
            'description' => 'Kategori Creative Innovation menantang tim peserta untuk merancang, membangun, dan mempresentasikan karya robotika inovatif bertema solusi masa depan. Peserta bebas menggunakan berbagai modul mikrokontroler, sensor cerdas, dan bahan kreatif.',
            'team_size' => 'Tim (2 - 3 Orang)',
            'price_normal' => 'Rp 425.000',
            'price_early' => 'Rp 399.000',
            'icon' => 'bulb',
            'image' => 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=800&auto=format&fit=crop',
            'juknis_url' => 'https://drive.google.com/',
            'evaluation_points' => [
                'Originalitas Ide & Kreativitas Konsep',
                'Fungsionalitas & Kompleksitas Sistem Robotika',
                'Penyampaian Presentasi & Demonstrasi Alat',
                'Dampak Solutif bagi Masyarakat / Lingkungan'
            ],
            'equipment' => 'Bebas (Arduino, ESP32, Raspberry Pi, LEGO, dll.)',
            'venue_note' => 'Area Display & Stand Presentasi SRC 2026'
        ],
        [
            'id' => 2,
            'slug' => 'innovative-challenge',
            'name' => 'Innovative Challenge',
            'type' => 'Tim',
            'category_badge' => 'Umur 12 - 18 Tahun',
            'target_level' => 'Kategori untuk Umur ( 12 - 18 Tahun )',
            'tagline' => 'Tantangan pemecahan misi teknis dengan logika pemrograman dinamis dan mekanika presisi.',
            'description' => 'Innovative Challenge menguji ketangkasan dan kemampuan analisis tim dalam menyelesaikan misi robotika terstruktur di arena khusus. Robot harus mampu membaca rintangan, bermanuver cerdas, dan mengeksekusi perintah secara efektif.',
            'team_size' => 'Tim (2 - 3 Orang)',
            'price_normal' => 'Rp 425.000',
            'price_early' => 'Rp 399.000',
            'icon' => 'puzzle',
            'image' => 'https://images.unsplash.com/photo-1563770660941-20978e870e26?q=80&w=800&auto=format&fit=crop',
            'juknis_url' => 'https://drive.google.com/',
            'evaluation_points' => [
                'Kecepatan & Ketepatan Penyelesaian Misi Arena',
                'Efisiensi Algoritma & Logika Pergerakan Robot',
                'Stabilitas Mekanik & Desain Konstruksi',
                'Kerjasama Tim & Strategi Bertanding'
            ],
            'equipment' => 'Mikrokontroler & Sensor sesuai regulasi teknis SRC',
            'venue_note' => 'Arena Misi Khusus Innovative Challenge'
        ],
        [
            'id' => 3,
            'slug' => 'robot-soccer-open-senior',
            'name' => 'Robot Soccer Open Senior',
            'type' => 'Individu',
            'category_badge' => 'Umur 12 - 18 Tahun',
            'target_level' => 'Kategori untuk ( 12 - 18 Tahun )',
            'tagline' => 'Pertandingan sepak bola robot tingkat mahir dengan kendali wireless dan strategi ofensif-defensif tinggi.',
            'description' => 'Robot Soccer Open Senior merupakan kompetisi adu strategi sepak bola robotik. Peserta mengendalikan robot untuk menggiring, mengoper, dan mencetak gol ke gawang lawan dalam durasi pertandingan yang telah ditentukan.',
            'team_size' => 'Individu (1 Peserta / Operator)',
            'price_normal' => 'Rp 225.000',
            'price_early' => 'Rp 199.000',
            'icon' => 'soccer',
            'image' => 'https://images.unsplash.com/photo-1535378917042-10a22c95931a?q=80&w=800&auto=format&fit=crop',
            'juknis_url' => 'https://drive.google.com/',
            'evaluation_points' => [
                'Jumlah Gol yang Berhasil Dicetak',
                'Ketangkasan Manuver & Penguasaan Bola',
                'Kekuatan Mekanik Dribbler / Kicker Robot',
                'Kedisiplinan & Sportivitas Bertanding'
            ],
            'equipment' => 'Robot Soccer Wireless / Bluetooth RC (Dimensi & Berat Terstandarisasi)',
            'venue_note' => 'Lapangan Resmi Robot Soccer SRC 2026'
        ],
        [
            'id' => 4,
            'slug' => 'robot-soccer-junior',
            'name' => 'Robot Soccer Junior',
            'type' => 'Individu',
            'category_badge' => 'Tingkat SD',
            'target_level' => 'Kategori untuk tingkat SD',
            'tagline' => 'Kompetisi sepak bola robot ramah pemula yang menyenangkan bagi siswa Sekolah Dasar.',
            'description' => 'Dirancang khusus bagi peserta tingkat Sekolah Dasar (SD) untuk melatih koordinasi motorik, reflek kontrol jarak jauh, serta membangun kepercayaan diri berkompetisi di panggung turnamen robotika nasional.',
            'team_size' => 'Individu (1 Peserta / Operator)',
            'price_normal' => 'Rp 225.000',
            'price_early' => 'Rp 199.000',
            'icon' => 'soccer-junior',
            'image' => 'https://images.unsplash.com/photo-1561557944-6e7860d1a7eb?q=80&w=800&auto=format&fit=crop',
            'juknis_url' => 'https://drive.google.com/',
            'evaluation_points' => [
                'Skor Gol Akhir Pertandingan',
                'Kontrol Halus & Pengendalian Robot',
                'Kepatuhan terhadap Garis Batas Lapangan',
                'Kemandirian & Semangat Sportivitas Siswa'
            ],
            'equipment' => 'Robot Soccer Kit Junior',
            'venue_note' => 'Mini Arena Robot Soccer SD'
        ],
        [
            'id' => 5,
            'slug' => 'line-follower',
            'name' => 'Line Follower',
            'type' => 'Tim',
            'category_badge' => 'Umur 12 - 18 Tahun',
            'target_level' => 'Kategori untuk umur ( 12 - 18 Tahun )',
            'tagline' => 'Balapan robot pelacak garis otomatis dengan kecepatan tinggi dan algoritma PID presisi.',
            'description' => 'Line Follower adalah ajang adu kecepatan dan kecerdasan algoritma navigasi otomatis. Robot tanpa kendali manual harus membaca lintasan garis gelap/terang, melewati tikungan tajam, percabangan, dan tanjakan dalam catatan waktu tercepat.',
            'team_size' => 'Tim (2 Orang)',
            'price_normal' => 'Rp 425.000',
            'price_early' => 'Rp 399.000',
            'icon' => 'route',
            'image' => 'https://images.unsplash.com/photo-1517055729445-fa7d27394b48?q=80&w=800&auto=format&fit=crop',
            'juknis_url' => 'https://drive.google.com/',
            'evaluation_points' => [
                'Waktu Tempuh Tercepat (Lap Time)',
                'Kemampuan Melewati Checkpoint Tanpa Keluar Lintasan',
                'Kestabilan Algoritma Sensor Optik / PID',
                'Kalibrasi Sensor yang Tepat di Arena'
            ],
            'equipment' => 'Robot Line Follower Analog / Microcontroller Autonomous',
            'venue_note' => 'Sirkuit Lintasan Karpet Garis SRC'
        ],
        [
            'id' => 6,
            'slug' => 'fast-building-sd',
            'name' => 'Fast Building SD',
            'type' => 'Individu',
            'category_badge' => 'Tingkat SD',
            'target_level' => 'Kategori untuk tingkat SD',
            'tagline' => 'Adu kecepatan dan ketelitian merakit konstruksi mekanik balok robotika bagi siswa SD.',
            'description' => 'Kompetisi merakit konstruksi robot sesuai panduan modul rahasia yang diumumkan pada saat pertandingan. Menguji konsentrasi, daya ingat visual, ketelitian mekanis, dan kecepatan tangan peserta.',
            'team_size' => 'Individu (1 Peserta)',
            'price_normal' => 'Rp 225.000',
            'price_early' => 'Rp 199.000',
            'icon' => 'blocks',
            'image' => 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?q=80&w=800&auto=format&fit=crop',
            'juknis_url' => 'https://drive.google.com/',
            'evaluation_points' => [
                'Kecepatan Waktu Penyelesaian Perakitan',
                'Kesesuaian 100% dengan Gambar Blueprint Soal',
                'Kekokohan dan Kerapian Sambungan Komponen',
                'Kemandirian Peserta saat Perakitan'
            ],
            'equipment' => 'Kit Konstruksi Balok Robotika Standar SRC',
            'venue_note' => 'Meja Perakitan Fast Building Hall'
        ],
        [
            'id' => 7,
            'slug' => 'fast-building-tk',
            'name' => 'Fast Building TK',
            'type' => 'Individu',
            'category_badge' => 'Tingkat TK',
            'target_level' => 'Kategori untuk tingkat TK',
            'tagline' => 'Stimulasi kreativitas, kecerdasan spasial, dan kecepatan motorik halus anak usia dini.',
            'description' => 'Ajang kompetisi edukatif dan menyenangkan untuk anak usia Taman Kanak-Kanak (TK). Peserta diajak merakit bentuk model bangunan dan mekanika sederhana dengan bimbingan juri yang ramah anak.',
            'team_size' => 'Individu (1 Peserta)',
            'price_normal' => 'Rp 225.000',
            'price_early' => 'Rp 199.000',
            'icon' => 'baby',
            'image' => 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=800&auto=format&fit=crop',
            'juknis_url' => 'https://drive.google.com/',
            'evaluation_points' => [
                'Ketepatan Susunan Model Bangun Sesuai Contoh',
                'Kecepatan & Kemandirian Anak',
                'Keceriaan & Keberanian Tampil Berkompetisi',
                'Kerapian Hasil Rakitan Balok'
            ],
            'equipment' => 'Kit Balok Konstruksi Usia Dini (Aman & Ramah Anak)',
            'venue_note' => 'Kids Innovation Zone SRC'
        ],
        [
            'id' => 8,
            'slug' => 'coding-scratch-sd',
            'name' => 'Coding Scratch SD',
            'type' => 'Individu',
            'category_badge' => 'Tingkat SD',
            'target_level' => 'Kategori lomba pemrograman menggunakan Scratch untuk tingkat SD',
            'tagline' => 'Tantangan logika computational thinking, pembuatan animasi interaktif & mini game edukasi.',
            'description' => 'Lomba pemrograman visual block-based menggunakan platform Scratch untuk siswa SD. Peserta diberikan studi kasus untuk membuat game interaktif atau animasi bertema sains dan lingkungan dalam durasi waktu tertentu.',
            'team_size' => 'Individu (1 Peserta)',
            'price_normal' => 'Rp 225.000',
            'price_early' => 'Rp 199.000',
            'icon' => 'code',
            'image' => 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=800&auto=format&fit=crop',
            'juknis_url' => 'https://drive.google.com/',
            'evaluation_points' => [
                'Logika Algoritma & Struktur Block Scratch',
                'Kreativitas Alur Cerita / Gameplay Interaktif',
                'Desain Visual & Efek Suara Animasi',
                'Fungsionalitas Program Tanpa Bug'
            ],
            'equipment' => 'Laptop / PC dengan Browser & Scratch 3.0 Offline/Online Editor',
            'venue_note' => 'Lab Komputer Universitas Nusa Putra'
        ],
        [
            'id' => 9,
            'slug' => 'sumo-1kg',
            'name' => 'Sumo 1 KG',
            'type' => 'Individu',
            'category_badge' => 'Umum & Edurobotik',
            'target_level' => 'Kategori usulan dari Edurobotik dan UMUM',
            'tagline' => 'Pertarungan robot Sumo kelas 1 KG penuh daya dorong mekanis dan ketangguhan taktik di ring Dohyo.',
            'description' => 'Kompetisi pertempuran robot Sumo berbobot maksimal 1 Kilogram. Dua robot diadu di atas ring lingkaran Dohyo resmi untuk saling mendorong keluar arena dengan kekuatan motor torsi tinggi dan taktik manuver tangguh.',
            'team_size' => 'Individu (1 Peserta / Operator)',
            'price_normal' => 'Rp 225.000',
            'price_early' => 'Rp 199.000',
            'icon' => 'shield',
            'image' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop',
            'juknis_url' => 'https://drive.google.com/',
            'evaluation_points' => [
                'Kemenangan Knock-out / Mendorong Lawan Keluar Dohyo',
                'Kepatuhan Batas Berat Max 1.000 Gram & Dimensi Robot',
                'Kecepatan Sensor Garis Tepi Dohyo & Sensor Jarak Lawan',
                'Ketahanan Mekanik Sasis & Blade Robot'
            ],
            'equipment' => 'Robot Sumo RC / Autonomous Kelas 1.000 Gram',
            'venue_note' => 'Ring Dohyo Pertandingan Sumo SRC'
        ],
        [
            'id' => 10,
            'slug' => 'sumo-close',
            'name' => 'Sumo Close',
            'type' => 'Individu',
            'category_badge' => 'Kategori Khusus Close',
            'target_level' => 'Kategori Close',
            'tagline' => 'Kompetisi eksklusif kategori Sumo Close dengan spesifikasi terstandardisasi khusus.',
            'description' => 'Kategori khusus Sumo Close yang mempertemukan peserta dalam format standarisasi kit tertutup. Menitikberatkan pada kemampuan strategi tanding, penyetelan presisi perangkat, dan kemampuan adaptasi operator.',
            'team_size' => 'Individu (1 Peserta / Operator)',
            'price_normal' => 'Rp 1.450.000',
            'price_early' => 'Rp 1.399.000',
            'icon' => 'award',
            'image' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?q=80&w=800&auto=format&fit=crop',
            'juknis_url' => 'https://drive.google.com/',
            'evaluation_points' => [
                'Poin Kemenangan Duel di Ring Dohyo Close',
                'Kepatuhan Standarisasi Kit Close',
                'Strategi Operator dalam Membaca Gaya Bertarung Lawan',
                'Stabilitas & Responsivitas Robot Saat Kontak'
            ],
            'equipment' => 'Kit Robot Sumo Close Resmi',
            'venue_note' => 'Ring Khusus Kategori Sumo Close'
        ]
    ]
];
